"""Change fields email_data

Revision ID: fb11b8a79512
Revises: ac7134a85097
Create Date: 2025-08-05 18:39:04.734740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb11b8a79512'
down_revision = 'ac7134a85097'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_data', sa.Column('template', sa.String(length=255), nullable=True), schema='emails')
    op.add_column('email_data', sa.Column('context', sa.JSON(), nullable=True), schema='emails')
    op.alter_column('email_data', 'status',
               existing_type=postgresql.ENUM('NEW', 'RETRY', 'PROCESSED', 'PROCESSING', 'ERROR', name='statustype', schema='emails'),
               type_=sa.Enum('NEW', 'RETRY', 'PROCESSED', 'PROCESSING', 'ERROR', name='statustype', schema='emails'),
               existing_nullable=True, schema='emails')
    op.drop_column('email_data', 'body', schema='emails')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_data', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True), schema='emails')
    op.alter_column('email_data', 'status',
               existing_type=sa.Enum('NEW', 'RETRY', 'PROCESSED', 'PROCESSING', 'ERROR', name='statustype', schema='emails'),
               type_=postgresql.ENUM('NEW', 'RETRY', 'PROCESSED', 'PROCESSING', 'ERROR', name='statustype', schema='emails'),
               existing_nullable=True, schema='emails')
    op.drop_column('email_data', 'context', schema='emails')
    op.drop_column('email_data', 'template', schema='emails')
    # ### end Alembic commands ###
