"""Change body email_data

Revision ID: 3b412ac003d5
Revises: cc019591570b
Create Date: 2025-08-06 16:52:51.931588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b412ac003d5'
down_revision = 'cc019591570b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_data', sa.Column('body', sa.Text(), nullable=True), schema='emails')
    op.alter_column('email_data', 'status',
               existing_type=postgresql.ENUM('NEW', 'RETRY', 'PROCESSED', 'PROCESSING', 'ERROR', name='statustype'),
               type_=sa.Enum('NEW', 'RETRY', 'PROCESSED', 'PROCESSING', 'ERROR', name='statustype', schema='emails'),
               existing_nullable=True, schema='emails')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_data', 'status',
               existing_type=sa.Enum('NEW', 'RETRY', 'PROCESSED', 'PROCESSING', 'ERROR', name='statustype', schema='emails'),
               type_=postgresql.ENUM('NEW', 'RETRY', 'PROCESSED', 'PROCESSING', 'ERROR', name='statustype'),
               existing_nullable=True, schema='emails')
    op.drop_column('email_data', 'body', schema='emails')
    # ### end Alembic commands ###
