"""Change jsonb email_data

Revision ID: cc019591570b
Revises: fb11b8a79512
Create Date: 2025-08-06 13:17:52.009548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc019591570b'
down_revision = 'fb11b8a79512'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_data', 'context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True, schema='emails')
    op.alter_column('email_data', 'status',
               existing_type=postgresql.ENUM('NEW', 'RETRY', 'PROCESSED', 'PROCESSING', 'ERROR', name='statustype'),
               type_=sa.Enum('NEW', 'RETRY', 'PROCESSED', 'PROCESSING', 'ERROR', name='statustype', schema='emails'),
               existing_nullable=True, schema='emails')
    op.alter_column('email_data', 'attachments',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True, schema='emails')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_data', 'attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True, schema='emails')
    op.alter_column('email_data', 'status',
               existing_type=sa.Enum('NEW', 'RETRY', 'PROCESSED', 'PROCESSING', 'ERROR', name='statustype', schema='emails'),
               type_=postgresql.ENUM('NEW', 'RETRY', 'PROCESSED', 'PROCESSING', 'ERROR', name='statustype'),
               existing_nullable=True, schema='emails')
    op.alter_column('email_data', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True, schema='emails')
    # ### end Alembic commands ###
